# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08e2712ed87fe999e4149a7e77ae75276e83e49760b0ecff76d38e86aefd8cae74d0a755f6fb1defb905b1d0ae2dd04bec5fb4902675abeceaeed2ffc5d27b58

test:
  secret_key_base: 96b5a7d6160d046a151d69d0b1f58516f513da04856445250d62978dfe64f5fc4d5b12e053a59b6c591f43780776d0ae0952af4e22cfaa99b99e8343e9b9525a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
